######################################################################
# Automatically generated by qmake (3.0) Wed Oct 30 14:10:13 2013
######################################################################

TARGET   = agent

TEMPLATE = lib
CONFIG  += staticlib

# Input
HEADERS += Agent.h   AgentBeep.h   AgentDisk.h   AgentDisplay.h   AgentFloppy.h   AgentKeyboard.h
SOURCES += Agent.cpp AgentBeep.cpp AgentDisk.cpp AgentDisplay.cpp AgentFloppy.cpp AgentKeyboard.cpp

HEADERS += AgentMouse.h   AgentNetwork.h   AgentProcessor.h   AgentStream.h   DiskFile.h   NetworkPacket.h
SOURCES += AgentMouse.cpp AgentNetwork.cpp AgentProcessor.cpp AgentStream.cpp DiskFile.cpp

HEADRES += StreamBoot.h   StreamCopyPaste.h   StreamPCFA.h   StreamTCP.h   StreamWWC.h
SOURCES += StreamBoot.cpp StreamCopyPaste.cpp StreamPCFA.cpp StreamTCP.cpp StreamWWC.cpp

unix {
	SOURCES += NetworkPacket.cpp
}
win32 {
	SOURCES += NetworkPacket_dummy.cpp
}

###############################################

INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++0x -Wall -Werror -g

contains(QT_MAJOR_VERSION, 4) {
        QMAKE_CXXFLAGS += -Wno-unused-local-typedefs
}

DESTDIR     = ../../tmp/build/$$TARGET
OBJECTS_DIR = ../../tmp/build/$$TARGET
MOC_DIR     = ../../tmp/build/$$TARGET
RCC_DIR     = ../../tmp/build/$$TARGET
UI_DIR      = ../../tmp/build/$$TARGET
