######################################################################
# Automatically generated by qmake (3.0) Wed Oct 30 14:24:50 2013
######################################################################

TARGET   = test
TEMPLATE = app

# Input
HEADERS += testBase.h
SOURCES += testBase.cpp

SOURCES += testAgent.cpp testMain.cpp testMemory.cpp testOpcode_000.cpp testOpcode_100.cpp testOpcode_200.cpp
SOURCES += testOpcode_300.cpp testOpcode_esc.cpp testPilot.cpp testType.cpp testByteBuffer.cpp

LIBS += ../../tmp/build/mesa/libmesa.a
LIBS += ../../tmp/build/opcode/libopcode.a
LIBS += ../../tmp/build/agent/libagent.a
LIBS += ../../tmp/build/util/libutil.a

LIBS += -lcppunit -llog4cpp

POST_TARGETDEPS += ../../tmp/build/mesa/libmesa.a
POST_TARGETDEPS += ../../tmp/build/opcode/libopcode.a
POST_TARGETDEPS += ../../tmp/build/agent/libagent.a
POST_TARGETDEPS += ../../tmp/build/util/libutil.a

###############################################

INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++0x -Wall -Werror -g

win32 {
	QMAKE_LFLAGS   += -static
}

contains(QT_MAJOR_VERSION, 4) {
        QMAKE_CXXFLAGS += -Wno-unused-local-typedefs
}

DESTDIR     = ../../tmp/build/$$TARGET
OBJECTS_DIR = ../../tmp/build/$$TARGET
MOC_DIR     = ../../tmp/build/$$TARGET
RCC_DIR     = ../../tmp/build/$$TARGET
UI_DIR      = ../../tmp/build/$$TARGET
