/*
Copyright (c) 2014, Yasuhiro Hasegawa
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
  3. The name of the author may not be used to endorse or promote products derived
     from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
OF SUCH DAMAGE.
*/


//
// Run_decl.h
//


RUN_DECL(1, FLAG_ARG_0, MOP_OPCODE_TRAP)
RUN_DECL(2, FLAG_ARG_0, ESC_OPCODE_TRAP)
RUN_DECL(3, FLAG_ARG_0, ESC)
RUN_DECL(4, FLAG_ARG_0, RESCHEDULE)


//
// Opcode_simple.cpp
//
// MOP
RUN_DECL(5, FLAG_ARG_0, NOOP)
RUN_DECL(6, FLAG_ARG_1, LL)
RUN_DECL(7, FLAG_ARG_1, LLD)
RUN_DECL(8, FLAG_ARG_1, SL)
RUN_DECL(9, FLAG_ARG_1, SLD)
RUN_DECL(10, FLAG_ARG_1, PL)
RUN_DECL(11, FLAG_ARG_1, PLD)
RUN_DECL(12, FLAG_ARG_1, LG)
RUN_DECL(13, FLAG_ARG_1, LGD)
RUN_DECL(14, FLAG_ARG_1, SG)
RUN_DECL(15, FLAG_ARG_0, BNDCK)
RUN_DECL(16, FLAG_ARG_0, BRK)
RUN_DECL(17, FLAG_ARG_1, R)
RUN_DECL(18, FLAG_ARG_1, RL)
RUN_DECL(19, FLAG_ARG_1, RD)
RUN_DECL(20, FLAG_ARG_1, RDL)
RUN_DECL(21, FLAG_ARG_1, W)
RUN_DECL(22, FLAG_ARG_1, PS)
RUN_DECL(23, FLAG_ARG_1, WL)
RUN_DECL(24, FLAG_ARG_1, PSL)
RUN_DECL(25, FLAG_ARG_1, WD)
RUN_DECL(26, FLAG_ARG_1, PSD)
RUN_DECL(27, FLAG_ARG_1, WDL)
RUN_DECL(28, FLAG_ARG_1, PSDL)
RUN_DECL(29, FLAG_ARG_2, RLI)
RUN_DECL(30, FLAG_ARG_2, RLIL)
RUN_DECL(31, FLAG_ARG_2, RLDI)
RUN_DECL(32, FLAG_ARG_2, RLDIL)
RUN_DECL(33, FLAG_ARG_2, RGI)
RUN_DECL(34, FLAG_ARG_2, RGIL)
RUN_DECL(35, FLAG_ARG_2, WLI)
RUN_DECL(36, FLAG_ARG_2, WLIL)
RUN_DECL(37, FLAG_ARG_2, WLDIL)
RUN_DECL(38, FLAG_ARG_1, RS)
RUN_DECL(39, FLAG_ARG_1, RLS)
RUN_DECL(40, FLAG_ARG_1, WS)
RUN_DECL(41, FLAG_ARG_1, WLS)
RUN_DECL(42, FLAG_ARG_2, RF)
RUN_DECL(43, FLAG_ARG_2, RLF)
RUN_DECL(44, FLAG_ARG_0, RLFS)
RUN_DECL(45, FLAG_ARG_2, RLIPF)
RUN_DECL(46, FLAG_ARG_2, RLILPF)
RUN_DECL(47, FLAG_ARG_2, WF)
RUN_DECL(48, FLAG_ARG_2, PSF)
RUN_DECL(49, FLAG_ARG_2, WSF)
RUN_DECL(50, FLAG_ARG_2, WLF)
RUN_DECL(51, FLAG_ARG_2, PSLF)
RUN_DECL(52, FLAG_ARG_0, WLFS)
RUN_DECL(53, FLAG_ARG_1, SGD)
RUN_DECL(54, FLAG_ARG_1, LLK)
RUN_DECL(55, FLAG_ARG_1, RKI)
RUN_DECL(56, FLAG_ARG_1, RKDI)
RUN_DECL(57, FLAG_ARG_1, LK)
RUN_DECL(58, FLAG_ARG_0, SHIFT)
RUN_DECL(59, FLAG_ARG_1, SHIFTI)
RUN_DECL(60, FLAG_ARG_1, CATCH)
RUN_DECL(61, FLAG_ARG_1, J)
RUN_DECL(62, FLAG_ARG_2, JUE)
RUN_DECL(63, FLAG_ARG_1, JEB)
RUN_DECL(64, FLAG_ARG_2, JUNE)
RUN_DECL(65, FLAG_ARG_1, JNEB)
RUN_DECL(66, FLAG_ARG_1, JLB)
RUN_DECL(67, FLAG_ARG_1, JGEB)
RUN_DECL(68, FLAG_ARG_1, JGB)
RUN_DECL(69, FLAG_ARG_1, JLEB)
RUN_DECL(70, FLAG_ARG_1, JULB)
RUN_DECL(71, FLAG_ARG_1, JUGEB)
RUN_DECL(72, FLAG_ARG_1, JUGB)
RUN_DECL(73, FLAG_ARG_1, JULEB)
RUN_DECL(74, FLAG_ARG_1, JZ)
RUN_DECL(75, FLAG_ARG_1, JNZ)
RUN_DECL(76, FLAG_ARG_1, JDE)
RUN_DECL(77, FLAG_ARG_1, JDNE)
RUN_DECL(78, FLAG_ARG_1, JIB)
RUN_DECL(79, FLAG_ARG_1, JIW)
RUN_DECL(80, FLAG_ARG_0, REC)
RUN_DECL(81, FLAG_ARG_0, REC2)
RUN_DECL(82, FLAG_ARG_0, DIS)
RUN_DECL(83, FLAG_ARG_0, DIS2)
RUN_DECL(84, FLAG_ARG_0, EXCH)
RUN_DECL(85, FLAG_ARG_0, DEXCH)
RUN_DECL(86, FLAG_ARG_0, DUP)
RUN_DECL(87, FLAG_ARG_0, DDUP)
RUN_DECL(88, FLAG_ARG_0, EXDIS)
RUN_DECL(89, FLAG_ARG_0, NEG)
RUN_DECL(90, FLAG_ARG_0, INC)
RUN_DECL(91, FLAG_ARG_0, DEC)
RUN_DECL(92, FLAG_ARG_0, DINC)
RUN_DECL(93, FLAG_ARG_0, DBL)
RUN_DECL(94, FLAG_ARG_0, DDBL)
RUN_DECL(95, FLAG_ARG_0, TRPL)
RUN_DECL(96, FLAG_ARG_0, AND)
RUN_DECL(97, FLAG_ARG_0, IOR)
RUN_DECL(98, FLAG_ARG_1, ADDI)
RUN_DECL(99, FLAG_ARG_0, ADD)
RUN_DECL(100, FLAG_ARG_0, SUB)
RUN_DECL(101, FLAG_ARG_0, DADD)
RUN_DECL(102, FLAG_ARG_0, DSUB)
RUN_DECL(103, FLAG_ARG_0, ADC)
RUN_DECL(104, FLAG_ARG_0, ACD)
RUN_DECL(105, FLAG_ARG_1, AL0I)
RUN_DECL(106, FLAG_ARG_0, MUL)
RUN_DECL(107, FLAG_ARG_0, DCMP)
RUN_DECL(108, FLAG_ARG_0, UDCMP)
RUN_DECL(109, FLAG_ARG_0, VMFIND)
RUN_DECL(110, FLAG_ARG_1, LI)
RUN_DECL(111, FLAG_ARG_1, LID)
RUN_DECL(112, FLAG_ARG_1, LA)
RUN_DECL(113, FLAG_ARG_1, GA)
RUN_DECL(114, FLAG_ARG_0, LP)
RUN_DECL(115, FLAG_ARG_1, LGA)
RUN_DECL(116, FLAG_ARG_1, DESC)
RUN_DECL(117, FLAG_ARG_0, RESRVD)
// ESC
RUN_DECL(118, FLAG_ARG_0, SM)
RUN_DECL(119, FLAG_ARG_0, GMF)
RUN_DECL(120, FLAG_ARG_0, SMF)
RUN_DECL(121, FLAG_ARG_0, DI)
RUN_DECL(122, FLAG_ARG_0, EI)
RUN_DECL(123, FLAG_ARG_0, XOR)
RUN_DECL(124, FLAG_ARG_0, DAND)
RUN_DECL(125, FLAG_ARG_0, DIOR)
RUN_DECL(126, FLAG_ARG_0, DXOR)
RUN_DECL(127, FLAG_ARG_0, ROTATE)
RUN_DECL(128, FLAG_ARG_0, DSHIFT)
RUN_DECL(129, FLAG_ARG_0, LINT)
RUN_DECL(130, FLAG_ARG_0, JS)
RUN_DECL(131, FLAG_ARG_0, RCFS)
RUN_DECL(132, FLAG_ARG_1, RC)
RUN_DECL(133, FLAG_ARG_0, UDIV)
RUN_DECL(134, FLAG_ARG_0, LUDIV)
RUN_DECL(135, FLAG_ARG_1, ROB)
RUN_DECL(136, FLAG_ARG_1, WOB)
RUN_DECL(137, FLAG_ARG_1, DSK)
RUN_DECL(138, FLAG_ARG_1, LSK)
RUN_DECL(139, FLAG_ARG_0, BNDCKL)
RUN_DECL(140, FLAG_ARG_0, NILCK)
RUN_DECL(141, FLAG_ARG_0, NILCKL)
RUN_DECL(142, FLAG_ARG_0, DMUL)
RUN_DECL(143, FLAG_ARG_0, SDIV)
RUN_DECL(144, FLAG_ARG_0, SDDIV)
RUN_DECL(145, FLAG_ARG_0, UDDIV)
RUN_DECL(146, FLAG_ARG_0, WRPSB)
RUN_DECL(147, FLAG_ARG_0, WRMDS)
RUN_DECL(148, FLAG_ARG_0, WRWP)
RUN_DECL(149, FLAG_ARG_0, WRWDC)
RUN_DECL(150, FLAG_ARG_0, WRPTC)
RUN_DECL(151, FLAG_ARG_0, WRIT)
RUN_DECL(152, FLAG_ARG_0, WRXTS)
RUN_DECL(153, FLAG_ARG_0, WRMP)
RUN_DECL(154, FLAG_ARG_0, RRPSB)
RUN_DECL(155, FLAG_ARG_0, RRMDS)
RUN_DECL(156, FLAG_ARG_0, RRWP)
RUN_DECL(157, FLAG_ARG_0, RRWDC)
RUN_DECL(158, FLAG_ARG_0, RRPTC)
RUN_DECL(159, FLAG_ARG_0, RRIT)
RUN_DECL(160, FLAG_ARG_0, RRXTS)


//
// Ocode_bitblt.cpp
//
RUN_DECL(161, FLAG_ARG_0, COLORBLT)
RUN_DECL(162, FLAG_ARG_0, BITBLT)


//
// Opcode_block.cpp
//
RUN_DECL(163, FLAG_ARG_0, BLT)
RUN_DECL(164, FLAG_ARG_0, BLTL)
RUN_DECL(165, FLAG_ARG_0, BLTC)
RUN_DECL(166, FLAG_ARG_0, BLTCL)
RUN_DECL(167, FLAG_ARG_0, BLTLR)
RUN_DECL(168, FLAG_ARG_0, BLEL)
RUN_DECL(169, FLAG_ARG_0, BLECL)
RUN_DECL(170, FLAG_ARG_0, CKSUM)
RUN_DECL(171, FLAG_ARG_0, BYTBLT)
RUN_DECL(172, FLAG_ARG_0, BYTBLTR)


//
// Opcode_control.cpp
//
RUN_DECL(173, FLAG_ARG_1, EFC)
RUN_DECL(174, FLAG_ARG_1, LFC)
RUN_DECL(175, FLAG_ARG_0, SFC)
RUN_DECL(176, FLAG_ARG_0, RET)
RUN_DECL(177, FLAG_ARG_1, KFC)
RUN_DECL(178, FLAG_ARG_0, AF)
RUN_DECL(179, FLAG_ARG_0, FF)
RUN_DECL(180, FLAG_ARG_0, PI)
RUN_DECL(181, FLAG_ARG_0, PO)
RUN_DECL(182, FLAG_ARG_1, XE)
RUN_DECL(183, FLAG_ARG_1, XF)


//
// Opcode_special.cpp
//
RUN_DECL(184, FLAG_ARG_0, CALLAGENT)
RUN_DECL(185, FLAG_ARG_0, MAPDISPLAY)
RUN_DECL(186, FLAG_ARG_0, STOPEMULATOR)
RUN_DECL(187, FLAG_ARG_0, VERSION)
RUN_DECL(188, FLAG_ARG_0, 214)
RUN_DECL(189, FLAG_ARG_0, 305)
RUN_DECL(190, FLAG_ARG_0, 306)


//
// Opcode_process.cpp
//
RUN_DECL(191, FLAG_ARG_0, ME)
RUN_DECL(192, FLAG_ARG_0, MX)
RUN_DECL(193, FLAG_ARG_0, MW)
RUN_DECL(194, FLAG_ARG_0, MR)
RUN_DECL(195, FLAG_ARG_0, NC)
RUN_DECL(196, FLAG_ARG_0, BC)
RUN_DECL(197, FLAG_ARG_0, REQ)
RUN_DECL(198, FLAG_ARG_0, SPP)


//
// Combined opcodes
//

// Pass 1
RUN_DECL(199, FLAG_ARG_4,  RECPLLIMULRECLGDDADDRL)
RUN_DECL(200, FLAG_ARG_3J, LLINCLLJULB)
RUN_DECL(201, FLAG_ARG_4,  LLDLLRLSSL)
RUN_DECL(202, FLAG_ARG_3,  LLDLLRLS)
RUN_DECL(203, FLAG_ARG_3,  LLLLADDSL)
RUN_DECL(204, FLAG_ARG_3,  LLDBLRLDIACD)
RUN_DECL(205, FLAG_ARG_3A, RLLLDACDSLD)
RUN_DECL(206, FLAG_ARG_3,  RLRLDIACDSLD)
RUN_DECL(207, FLAG_ARG_3A, LLLLDACDRL)
RUN_DECL(208, FLAG_ARG_3J, LLLLJLB)
RUN_DECL(209, FLAG_ARG_3C, RLILSL)
RUN_DECL(210, FLAG_ARG_4,  SLLLLLADDSL)
RUN_DECL(211, FLAG_ARG_4,  LLDECDBLRLDIACDWDL)
RUN_DECL(212, FLAG_ARG_4,  LLDECDBLRLDIACDRDL)
RUN_DECL(213, FLAG_ARG_2,  LLJNEB)
RUN_DECL(214, FLAG_ARG_3J, PLLLJNEB)
RUN_DECL(215, FLAG_ARG_3,  LKSLSL)
RUN_DECL(216, FLAG_ARG_3,  LKSLPLDBL)
RUN_DECL(217, FLAG_ARG_4,  RLDIACDRLSL)
RUN_DECL(218, FLAG_ARG_4,  RLSLRLDI)
RUN_DECL(219, FLAG_ARG_3,  LLDECLLRD)
RUN_DECL(220, FLAG_ARG_4,  LALLPSF)
RUN_DECL(221, FLAG_ARG_3,  LLDUPDECLLRD)
RUN_DECL(222, FLAG_ARG_3,  PLDBLPLLL)
RUN_DECL(223, FLAG_ARG_2,  LLJULB)
RUN_DECL(224, FLAG_ARG_3,  SLDRLDIL)
RUN_DECL(225, FLAG_ARG_1,  MULRECLLDDADD)
RUN_DECL(226, FLAG_ARG_2,  LLJUGB)
RUN_DECL(227, FLAG_ARG_2,  IORJZ)
RUN_DECL(228, FLAG_ARG_1,  LLDUDCMP)
RUN_DECL(229, FLAG_ARG_2,  LLJGB)
RUN_DECL(230, FLAG_ARG_2,  LLSHIFTI)
RUN_DECL(231, FLAG_ARG_2,  LLJEB)
RUN_DECL(232, FLAG_ARG_2,  IORJNZ)


// Pass 2
RUN_DECL(233, FLAG_ARG_3,  SLLLLL)
RUN_DECL(234, FLAG_ARG_2,  LLLL)
RUN_DECL(235, FLAG_ARG_2,  LKSL)
RUN_DECL(236, FLAG_ARG_2,  LLLI)
RUN_DECL(237, FLAG_ARG_2,  SLDSLD)
RUN_DECL(238, FLAG_ARG_3,  SLDSLDSLD)
RUN_DECL(239, FLAG_ARG_2,  LIJ)
RUN_DECL(240, FLAG_ARG_2,  LLJ)
RUN_DECL(241, FLAG_ARG_1,  LLINC)
RUN_DECL(242, FLAG_ARG_2,  LLDLLD)
RUN_DECL(243, FLAG_ARG_1,  RECSL)
RUN_DECL(244, FLAG_ARG_1,  LLDACD)
RUN_DECL(245, FLAG_ARG_2,  LLDLL)
RUN_DECL(246, FLAG_ARG_2,  LLDLI)
RUN_DECL(247, FLAG_ARG_2,  PLLI)
RUN_DECL(248, FLAG_ARG_1,  LALP)
RUN_DECL(249, FLAG_ARG_2,  LLWSF)
RUN_DECL(250, FLAG_ARG_2,  LISL)
RUN_DECL(251, FLAG_ARG_2,  LALI)
RUN_DECL(252, FLAG_ARG_2,  SLDLLD)
RUN_DECL(253, FLAG_ARG_2,  SLLL)
